### ISSUE TITLE
InvalidStateError at not awaited task connection.close

### ISSUE THREAD

**Issue by khasanovbi** [micro-fan/aiozk#70]
Looks like there is 2 problems:
1) InvalidStateError at connection.close
2) Not awaited tasks at https://github.com/micro-fan/aiozk/blob/master/aiozk/session.py#L124, https://github.com/micro-fan/aiozk/blob/master/aiozk/session.py#L127
```
states.py:50 - transition_to() DEBUG --- Session transition: connected -> suspended
session.py:179 - repair_loop() DEBUG --- Repair state reached
session.py:109 - find_server() INFO --- Connecting to localhost:2182
connection.py:75 - connect() DEBUG --- Initial connection to server localhost:2182
connection.py:57 - _make_handshake() DEBUG --- Sending 'srvr' command to localhost:2182
connection.py:69 - _make_handshake() DEBUG --- Version info: (3, 6, 1)
connection.py:70 - _make_handshake() DEBUG --- Read-only mode: False
connection.py:72 - _make_handshake() DEBUG --- Actual connection to server localhost:2182
session.py:113 - find_server() INFO --- Connected to localhost:2182
session.py:123 - find_server() DEBUG --- Close old connection
base_events.py:1619 - default_exception_handler() ERROR --- Task exception was never retrieved
future: <Task finished coro=<Connection.close() done, defined at /Users/bkhasanov/Envs/ipv4mgr/lib/python3.7/site-packages/aiozk/connection.py:256> exception=InvalidStateError('invalid state')>
Traceback (most recent call last):
  File "/Users/bkhasanov/Envs/ipv4mgr/lib/python3.7/site-packages/aiozk/connection.py", line 264, in close
    await self.read_loop_task
  File "/Users/bkhasanov/Envs/ipv4mgr/lib/python3.7/site-packages/aiozk/connection.py", line 170, in read_loop
    f.set_exception(response)
asyncio.base_futures.InvalidStateError: invalid state
```

**Comment by rhdxmr** [comment]
@khasanovbi
I'll look into it
Thanks,

**Comment by khasanovbi** [comment]
Hi, the second problem is not fixed, fire-and-forget is bad pattern for asyncio, maybe aiojobs will help in this case.

**Comment by rhdxmr** [comment]
Hi @khasanovbi 

I agree with you. At line no 127, .find_server task is created and forgot. This can make multiple number of .find_server tasks run simultaneously. Thus this can incur undefined behavior. I am going to fix it soon.

At line no 124, old_conn.close task is created. But I think it is not bad because we do not need to spend time on waiting for closing the obsolete connection and fire-and-forget saves the time.

Thanks,
